apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: default
type: Opaque
data:
  client-id: bXkta2V5Y2xvYWstY2xpZW50
  client-secret: UjRFSlh1VU5YSlVXN1RqaFFxTmxCekU3T0Q1T1p0Ylo=
  cookie-secret: MTk3N1hhYUkzcGl5bjZCTWZSRGRPcFgzUkJ2M1V1VSs=

