apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  volumeName: postgres-pv     # ✅ Bind to your static PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

